### ISSUE TITLE
Layout/DotPosition: leading considered  harmful

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/oss-guides#67] opened 2023-11-08 13:09 UTC
We have flipped Layout/DotPosition from trailing to leading in the latest update to the Ribose house style. This seems to have somehow been inherited by the upgrade to Ruby 3.1, and reflects the Rubocop default.

````
# From 322cb2c179a721fed382a691124185a01811cf11
Layout/DotPosition:
  EnforcedStyle: leading
````

It may well be the Rubocop default, but it also goes against what we have been doing for years, and it impedes legibility. (It also breaks my autoformatter.) Surely internal Ribose consistency counts for more than what the Rubocop default is: we shouldn't be changing this by implicit inheritance.

**Comment by ribose-jeffreylau** [comment] 2023-11-09 07:47
@opoudjis Thanks for pointing out.  There's one issue that confuses me, which is that this setting has been set to `leading` since year 2020 (from commit 322cb2c179a721fed382a691124185a01811cf11), and only just been reverted to `trailing` recently (commit 45f25fe0af9f0b95908e4bbf70fc62da5e8c6136) in the compiled output (`ci/rubocop.yml`).  So what you're seeing should be the effect of `trailing`?

Anyhow, I've identified the cause of discrepancies between older commits and recent changes, which can be traced to the difference of different implementations of `deep_merge()`.  A fix is incoming, which correctly makes the Ribose input guide (with `leading`) take effect in the compiled output guide.  Though I think I need clarification on what is actually desired --- `leading` or `trailing`.  And if it's indeed `trailing` that is desired, then the question arises as to why `EnforcedStyle: trailing` would act like it's `EnforcedStyle: leading`.

**Comment by opoudjis** [comment] 2023-11-09 08:26
I desire dot in second line = trailing, and I share your confusion that we are getting the reverse behaviour from the configuration.

**Closed as completed** 2023-11-09 09:50 UTC
